[package]
name = "xaum"
description = "Xaum token contract"
version = "0.0.0"
edition = "2021"
rust-version = "1.89.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = { workspace = true }
soroban-token-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
